import { defineConfig } from 'wxt'

// Read directly from `process.env`, not from `src/core/config.ts`: the manifest below is
// generated by Node at build time, while `config.ts` is bundled into the extension itself
// and reads `import.meta.env` (inlined by Vite). Same variable, two different places to
// read it, because the two run in different processes.
const passOrigin = process.env.WXT_PASS_ORIGIN ?? 'https://pass.cfabric.org'

export default defineConfig({
  srcDir: 'src',
  modules: ['@wxt-dev/module-react'],
  manifest: () => ({
    name: '__MSG_extName__',
    description: '__MSG_extDescription__',
    default_locale: 'en',
    // `alarms` drives an hourly sweep of the pass cache (added in a later phase) — without
    // it an expired cache would linger in storage until the next resolve call touched it.
    permissions: ['storage', 'alarms'],
    // `https://github.com/*` and `https://raw.githubusercontent.com/*` are gone: after the
    // pass migration nothing in the extension fetches GitHub anymore. The content script
    // still runs on GitHub pages, but that's declared via its own `matches:`, which needs
    // no host permission. If `new URL(passOrigin)` throws because of a malformed env value,
    // let it throw — a broken build is better than a silently wrong host permission.
    host_permissions: [`${new URL(passOrigin).origin}/*`],
    // Stays for the URL source (T9): the user grants it interactively for one domain via
    // `permissions.request` when they add a source by URL.
    optional_host_permissions: ['*://*/*'],
  }),
})
